package com.flowiq.agents.architecture.model;

public enum DriftIssueType {
    ENDPOINT_WITHOUT_DOCUMENTATION,
    DOCUMENTATION_WITHOUT_ENDPOINT,
    SERVICE_WITHOUT_TESTS,
    CONTROLLER_WITHOUT_CONTRACT_TESTS,
    PAGE_WITHOUT_UI_TESTS,
    DTO_WITHOUT_SCHEMA
}
