package com.flowiq.agents.gap.model;

public enum GapType {
    NO_TEST_COVERAGE,
    MISSING_CONTRACT_COVERAGE,
    MISSING_SMOKE_COVERAGE,
    MISSING_REGRESSION_COVERAGE,
    MISSING_UI_COVERAGE,
    MISSING_UPDATE_TEST,
    MISSING_DELETE_TEST,
    MISSING_NEGATIVE_SCENARIO,
    MISSING_AUTHORIZATION_CHECK
}
