package com.flowiq.agents.orchestrator.model;

public enum QualityAgentType {
    API_CHANGE_DETECTION,
    TEST_GAP_ANALYZER,
    FLAKY_TEST_INVESTIGATOR,
    SMART_TEST_GENERATOR,
    RELEASE_RISK_ASSESSMENT,
    REQUIREMENTS_TRACEABILITY,
    SELF_HEALING_LOCATOR,
    TEST_REVIEW,
    ROOT_CAUSE_ANALYSIS,
    RISK_BASED_REGRESSION,
    ARCHITECTURE_DRIFT
}
