env=stage
base.url=https://flowiq.vercel.app
api.url=https://api.flowiq.ai
api.timeout=45000
ui.timeout=45000
browser=chromium
headless=true
slow.mo=0
test.user.email=${TEST_USER_EMAIL}
test.user.password=${TEST_USER_PASSWORD}
db.url=${DB_URL}
db.username=${DB_USERNAME}
db.password=${DB_PASSWORD}
