package com.flowiq.agents.factory.model;

public enum FactoryAgentType {
    PULL_REQUEST_REVIEW,
    TEST_REVIEW,
    API_CHANGE_DETECTION,
    RISK_BASED_REGRESSION,
    ARCHITECTURE_DRIFT,
    REQUIREMENTS_TRACEABILITY,
    TEST_GAP_ANALYZER,
    TEST_MAINTENANCE,
    ROOT_CAUSE_ANALYSIS,
    FLAKY_TEST_INVESTIGATOR,
    SELF_HEALING_LOCATOR,
    RELEASE_RISK_ASSESSMENT,
    SMART_TEST_GENERATOR
}
